
export const ADD_TO_CART = 'ADD_TO_CART';
export type ADD_TO_CART = typeof ADD_TO_CART;//typeof the above constant - ADD_TO_CART

export const CLEAR_ID_FROM_CART = 'CLEAR_ID_FROM_CART';
export type CLEAR_ID_FROM_CART = typeof CLEAR_ID_FROM_CART;

export const ADD_QUANTITY_TO_ITEM = 'ADD_QUANTITY_TO_ITEM';
export type ADD_QUANTITY_TO_ITEM = typeof ADD_QUANTITY_TO_ITEM;

export const REMOVE_QUANTITY_FROM_ITEM = 'REMOVE_QUANTITY_FROM_ITEM'
export type REMOVE_QUANTITY_FROM_ITEM = typeof REMOVE_QUANTITY_FROM_ITEM

export const REMOVE_ALL_QUANTITY_FROM_ITEM = 'REMOVE_ALL_QUANTITY_FROM_ITEM'
export type REMOVE_ALL_QUANTITY_FROM_ITEM = typeof REMOVE_ALL_QUANTITY_FROM_ITEM
