
export const ADD_TO_CART = 'ADD_TO_CART';
export type ADD_TO_CART = typeof ADD_TO_CART;//typeof the above constant - ADD_TO_CART

export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export type REMOVE_FROM_CART = typeof REMOVE_FROM_CART;

export const ADD_QUANTITY_TO_ITEM = 'ADD_QUANTITY_TO_ITEM';
export type ADD_QUANTITY_TO_ITEM = typeof ADD_QUANTITY_TO_ITEM;

export const REMOVE_QUANTITY_FROM_ITEM = 'REMOVE_QUANTITY_FROM_ITEM'
export type REMOVE_QUANTITY_FROM_ITEM = typeof REMOVE_QUANTITY_FROM_ITEM